# -*- coding: utf-8 -*-
"""Data Analysis with IMDB Movie data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D8IQKVV_lbkNvui5B1Y7IVMka0ht4zpn
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset_path = '/content/IMDB-Movie-Data.csv'
data = pd.read_csv(dataset_path)
data.head()

data_indexed = pd.read_csv(dataset_path, index_col = 'Title')
data_indexed.head()

data.info()

genre = data['Genre']
genre

data[['Genre']]

some_cols = data[['Title', 'Genre', 'Actors', 'Director', 'Rating']]
some_cols

# Verify the actual column names in your DataFrame
print(data.columns)

# If the column name is slightly different, correct it in your code
data.iloc[10:15][['Title', 'Rating', 'Revenue (Millions)']]  # Example correction, remove space

data [((data['Year'] >= 2010) & (data['Year'] <= 2015))
& (data['Rating']< 6.0)
& (data['Revenue (Millions)'] > data['Revenue (Millions)'].quantile(0.95))]

data.groupby('Director')[['Rating']].mean().head()

data.groupby('Director')[['Rating']].mean().sort_values(by = 'Rating', ascending = False).head()

data . isnull () .sum ()

data.drop('Metascore', axis = 1).head()

revenue_means = data_indexed[['Revenue (Millions)']].mean()
print ('The mean revenue is: ', revenue_means)
data_indexed[['Revenue (Millions)']].fillna(revenue_means, inplace = True)

def rating_group (rating):
  if rating >= 7.5:
    return 'Good'
  elif rating >= 6.0:
    return 'Average'
  else:
    return 'Bad'
data['Rating_category'] = data['Rating'].apply(rating_group)
data[['Title', 'Director', 'Rating', 'Rating_category']].head(5)